project_identifier: test-lephare
api_key: 9a32ca14790c9ec64bb11cbdbbf798be
base_path: /
preserve_hierarchy: true
files:
  - source: /app/Resources/Translation/*
    translation: /app/Resources/Translation/%file_name%.%two_letters_code%.%file_extension%
